### ISSUE TITLE
DigiTool migration of "PDF books"

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#1]
UF's DigiTool FHP collection has approx. 60 "PDF books".  These are objects with METS used to display TOC in DigiTool and linked PDF files.  Currently we have no mechanism for supporting PDF datastreams for books.  The IA Bookreader seems to have some options associated with PDFs, but I can’t tell if they would work in this instance: https://github.com/jsicot/BookReader).

Priscilla had identified “PDF books” as a category of materials, and we’re starting to encounter them.  We’ll need to discuss how these might be handled.  Some options might be to convert the PDFs to page images, but this will make the METS inaccurate.

This will need to be discussed and resolved before UF's DigiTool migration can be completed.  I'm opening this issue so that it can be discussed in January.

**Comment by lydiam** [comment]
Note that we're starting discussions with UF regarding a Sobek to Islandora migration, so it's possible that UF will ask to have those materials migrated from Sobek instead of DigiTool, so let's wait on this one.

**Comment by wrandtkeflvc** [comment]
PDFs were all migrated.  Either loaded as PDFs or Adobe Acrobat Professional used to extract an image of each page.
