### ISSUE TITLE
Support for new mods-3-5.xsd

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#10]
The MODS schema has been updated, and the latest version is mods-3-5.xsd, released in July 2013. (Changes are documented at: http://www.loc.gov/standards/mods/changes-3-5.html)  To date FL-Islandora has been using mods-3-4.xsd and we need to explore support for the new version.

There are a number of components to this project:
1.  Jonathan Pitts programmed the Excel to MODS transformer to reference mods-3-5.xsd (although I don't believe that he uses any of the new 3-5.xsd features), but FL-Islandora doesn't yet support that version.  Gerald is looking into setting the Transformer code back to mods-3-4.xsd until we can determine how we want to proceed with mods-3-5.xsd.
2. Unattended batch ingest, and possibly the package program to date have been expecting mods-3-4.xsd.
3.  Formbuilder forms reference mods-3-4.xsd, and we don't know the implications for editing between schema versions.
4.  FL-Islandora displays are hard-coded, and introduction of new mods-3-5.xsd attributes may affect Islandora Full Description displays. (mike to provide reference to current display documentation)
5.  FL-Islandora MARC to MODS transformations could be affected.  See http://www.loc.gov/standards/mods/mods-mapping.html

There may be additional components we haven't considered yet.  We'll need to explore all of the implications for allowing support for the new version of MODS.

**Comment by grf** [comment]
On Tue, Jan 6, 2015 at 1:38 PM, Lydia Motyka <notifications@github.com>
wrote:

> Unattended batch ingest, and possibly the package program to date have
> been expecting mods-3-4.xsd.
>
> Formbuilder forms reference mods-3-4.xsd, and we don't know the
> implications for editing between schema versions.
>

Actually,  version  1 through 4 are supported.

**Comment by lydiam** [comment]
How do we know that version 1 through 4 are supported?  Does this have any implications for supporting 3.5 in FormBuilder?

**Comment by mdemers** [comment]
For #5: All transformations used involving MODS mapping will need to accommodate any changes in 3.5: MODS2MARC, post-processing, and DC2MODS (though the latter probably won't be affected at all).

**Comment by mdemers** [comment]
I've created a limited 3.5 form on dev and tested it a bit. So far it can successfully create valid 3.5 MODS as well as update 3.4 MODS with or without updating the schemaLocation to 3.5. The current Full MODS form can also access and update 3.5 MODS with no problem. 

If you add 3.5 elements/attributes to a MODS datastream with the 3.4 schema it will be invalid -but the formbuilder does not recognize this so far. 

I haven't seen any issues of the display getting wonky with 3.5 yet but I've only added a single change. I can move ahead and try to work in all of the 3.5 changes into my form on dev if we're ready.

**Comment by grf** [comment]
On Tue, Jan 6, 2015 at 2:50 PM, mdemers <notifications@github.com> wrote:

> I haven't seen any issues of the display getting wonky with 3.5 yet but
> I've only added a single change. I can move ahead and try to work in all of
> the 3.5 changes into my form on dev if we're ready.



I'd be really surprised if it wasn't backwardly (and I do mean backward
here) compatible.

I guess we need a plan for checking for all the new elements/attributes and
see how they display:

  http://www.loc.gov/standards/mods/changes-3-5.html

I think most are non issues,  but I'm not a librarian....

**Comment by mdemers** [comment]
MODS should be almost entirely backwards compatible -I would hope. We’ve had problems in the past with unanticipated attributes and subelements goofing with the record display.

**Comment by mdemers** [comment]
The following documentation will need to be reviewed and/or updated on http://wiki.fcla.edu/wiki/index.php/DL:Islandora#Specs_and_Requirements and https://islandora.pubwiki.fcla.edu/wiki/index.php/Main_Page#Metadata when moving to 3.5

[Full MODS](https://docs.google.com/spreadsheets/d/1eywxce_wVw3Nfdy3hiOtgC_p8bZ_XKdkNtbMTM1XeBs/edit#gid=0)

[MODS object - All Labels](https://docs.google.com/document/d/1QFesjeuSVyL8gezlx4dWpOqOpvDG5vHCphueHQsge6I/edit)

Links pointing to the schema and mapping of 3.4 in these wikis will need to be updated as well.

**Comment by lydiam** [comment]
I’m going to discuss MODS 3.5 with ISG next Tuesday, so at this point we don’t know what would need to be added to forms, etc.  Our policy should be to never knowingly create invalid MODS, which means that if we change forms to accommodate new 3.5 attributes we should have FormBuilder update the schemalocation to 3.5 as well.  We don’t believe that Islandora every validates MODS itself and we’ve seen plenty of instances where invalid METS was allowed in DigiTool creating problems for us in the migration to Islandora, so the onus is on us to prevent loading of invalid MODS into Islandora.

**Comment by lydiam** [comment]
Mentioned at 1/20/15 ISG meeting, but needs follow-up.  Nobody immediately insisted that MODS 3.5 needs to be supported.

Idea:  should we have a Full MODS 3.4 form and another Full MODS 3.5 form?

**Comment by grf** [comment]
On Thu, Jan 22, 2015 at 10:45 AM, Lydia Motyka <notifications@github.com>
wrote:

> Idea: should we have a Full MODS 3.4 form and another Full MODS 3.5 form?


I should think we don't want to maintain both if we can avoid it -
presumably we're supporting 3.4, 3.3, 3.2...  with that one form.

**Comment by mdemers** [comment]
MODS 3.6 is on the way. So far the approved changes will have a greater impact than 3.5. 
http://www.loc.gov/standards/mods/changes-3-6.html

I believe all of our existing MODS in islandora would validate fine against a 3.6 schema but we'll need to add a number of things to the display and forms if we want to keep up.
