### ISSUE TITLE
FAMU books: broken link for certain pages in bookreader

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#11]
Debra discovered that certain pages in FAMU books don't display in bookreader, and instead display a broken link icon.  In the page viewer the JPG thumbnail displays fine, but the JP2 displays a blank page.  Regenerating the JP2 doesn't fix the problem.  An example is https://famu.digital.flvc.org/islandora/object/famu%3A1381, page 122 of the book.  The PDF derivative looks fine.

**Comment by lydiam** [comment]
Gail will take a quick look.

**Comment by wrandtkeflvc** [comment]
This is part of a bug, which I thought was separately reported, to where when a page is mostly whitespace, Islandora doesn't render the display derivatives for the sea dragon viewer.  Regenerating derivatives just now today fixed this particular page.  I'm going to go ahead and close this issue.

Presumably there are a whole bunch of these pages spread across the Islandora sites, and if there's a list somewhere of those, someone could click through it and "Regenerate derivatives" for the blank pages.
