### ISSUE TITLE
Breaking up UF batch MARCXML file for DigiTool FHP migration

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#13]
Sent to Gerald 12/18 for Liang to work on .

Converted packages that need replacement of MARC/MODS can be found in /ssa/d2i/UF_FHP_book_export_converted.

File of MARCXML records emailed to Gerald (there seems to be no way of just attaching a text file into GitHub issues).

The file sent to us by UF (I’m hoping for a replacement file that includes only the MARC records we actually need) is O:\Digital Services\Islandora\UF DigiTool/marc_report.xml.

It’s a single file of a few thousand MARC records, and the <record> field is the delimiter between records.

What I think needs to be done:
• Each <record>.*</record> section should constitute a new XML file and needs to contain a valid header. (I can provide the exact header in a subsequent email, if necessary)
• Each individual new file should be named after the contents of the <controlfield tag="001"> contents.  So the record in the file that contains <controlfield tag="001">AA00000106_00001</controlfield> would at the end of this process be a file named AA00000106_00001.xml

There will be a later component that would need to match the MARCXML filenames against converted DigiTool packages, and the MARCXML files would need to be transformed into MODS and the new MODS files would need to replace the old ones in the DigiTool packages.

Some examples of the names UF DigiTool packages after conversion to Islandora packages (from a different collection):

UF00000100  UF00000223  UF00000976  UF00001094  UF00001147  UF00001235  UF00001512  UF00001560  UF00002308  UF00002925  UF00003040    UF00003086  UF00005236
UF00000103  UF00000227  UF00000977  UF00001096  UF00001148  UF00001236  UF00001513  UF00001561  UF00002309  UF00002926  UF00003041    UF00003183  UF00005237
UF00000104  UF00000234  UF00000978  UF00001097  UF00001149  UF00001237  UF00001514  UF00001562  UF00002310  UF00002927  UF00003042    UF00003184  UF00005238

Attached is a file of IDs extracted from converted DigiTool MODS.  Some of the IDs in that file either fully or partially match the 001 fields in UF’s MARC file.  UF says that it’s OK to truncate their 001s if we don’t find a match.  I’m hoping that UF will send us a smaller file of only those MARCXML records that they find to match the IDs in the DigiTool records.

Even if UF sends us the smaller file of records we may need to end up doing the two-level comparison (untruncated, if no match truncated at the _).  For example:  UF00000223  vs UF00000223_00001

**Comment by lydiam** [comment]
Liang was supposed to work on this, but given the current negotiations with UF re: Sobek to Islandora migration and UF's stated preference that their materials be loaded into Islandora from Sobek I'm putting this on hold.

**Comment by lydiam** [comment]
Email thread with Chelsea re: FHP collection that's relevant to this request:

From: Dinsmore, Chelsea S [mailto:chedins@uflib.ufl.edu] 
Sent: Thursday, December 18, 2014 4:19 PM
To: Lydia Motyka
Cc: Walker,Benjamin F; Botero,Cecilia
Subject: RE: Questions about UFDC Florida History and Heritage Collection vs. PALMM Florida Heritage Collection

Hi Lydia,

I believe the 600-700 titles is about right—based on the list you sent me, and then our FHPC collection continued to grow here.  I will try and figure out a way to reduce the set I am sending to something with fewer “extras” but it will take time to do that.  

We have been on hiatus from OAI feeds, but they have resumed, so all public items in UFDC are ready to be harvested by FLVC.

I don’t believe that everything in FHPC is PALMM—but most of our PALMM materials come from that collection—hence my choice to send that set to you.

I am going to defer my answer on that last bullet until final agreements have been reached with regards to Lucy’s letter.

I appreciate your efforts to untangle this situation.  

Chelsea


From: Lydia Motyka [mailto:LMotyka@flvc.org] 
Sent: Wednesday, December 17, 2014 10:08 AM
To: Dinsmore, Chelsea S
Subject: Questions about UFDC Florida History and Heritage Collection vs. PALMM Florida Heritage Collection

Chelsea,

At Monday’s meeting it was mentioned that UFDC/Sobek contains more PALMM? Florida Heritage Collection materials than does DigiTool, and there was some mention that UF wasn’t even aware that UF materials were loaded into DigiTool and presented as part of the Florida Heritage Collection (http://palmm.fcla.edu/fhp/).  Given that we’re having some trouble attempting to replace UF DigiTool FHP MARC metadata with newer MARC metadata from Sobek I’d like to better understand the “fhpc” collection on Sobek.  

I’ve got the following questions:
•         What is your estimate of the amount of duplication of materials between the two collections?  If the marc_report file is an indication, it looks like at most it might be 600-700 titles when I try to do a rough comparison of matches between the marc_report and a list of DigiTool 598 fields.
•         Is metadata from all UFDC FHPC objects being contributed to Mango?  (Note that FLVC simply loads any Mango feeds that UF provides and does not do an analysis of the contents.  Whatever UF chooses to provide in terms of Mango metadata FLVC will load.)
•         Does UF consider the UFDC FHPC collection a “PALMM collection”?  I’ve done a little searching of the collection and I don’t see any mention of PALMM or PALMM branding.  That makes me wonder how the UFDC FHPC materials fit into the PALMM framework.  In addition, DISC had stipulated that PALMM collections would not be split between platforms, but if UFDC FHPC is considered a PALMM collection this has already happened.
•         If UFDC FHPC materials are not currently considered PALMM materials, does UF want to include them in a single PALMM collection hosted on a single platform, as per the DISC stipulation?   (In the DISC meeting it was decided that this platform would be FL-Islandora.)  If not, then this whole issue would need to be revisited.

**Comment by lydiam** [comment]
Email to Chelsea:

From: Lydia Motyka 
Sent: Friday, January 09, 2015 9:33 AM
To: 'Dinsmore, Chelsea S'
Cc: 'Walker,Benjamin F'; 'Botero,Cecilia'; Lucy Harrison
Subject: RE: Questions about UFDC Florida History and Heritage Collection vs. PALMM Florida Heritage Collection

Chelsea,

Given the recent discussions about a Sobek to Islandora migration and the open questions about the nature of the Sobek FHPC collection I’m in a quandary as to whether I should continue working on the migration of UF DigiTool FHP materials into Islandora.  I’m perfectly willing to continue work on the migration, but I’m concerned about any future decisions about the Sobek FHPC collection affecting this work.  Can we agree that we’ll continue working on the migration of UF DigiTool FHP materials into Islandora and that the Sobek FHPC collection will be treated separately as part of the Sobek to Islandora migration?  If not I’ll put the DigiTool to Islandora FHP migration on hold.

Thanks,

Lydia

**Comment by lydiam** [comment]
No longer on hold.  Chelsea's email (she'll be sending only the records relevant to the packages exported from DigiTool, sometime next week):

From: Dinsmore, Chelsea S [mailto:chedins@uflib.ufl.edu] 
Sent: Monday, January 12, 2015 9:47 AM
To: Lydia Motyka
Cc: Walker,Benjamin F; Botero,Cecilia; Lucy Harrison
Subject: RE: Questions about UFDC Florida History and Heritage Collection vs. PALMM Florida Heritage Collection

Hi Lydia,

I propose that we provide you with the marcxml (in one batch file) for the PALMM mongraphs from the list you provided.  We have a refreshed marcxml tool coming online this week, so I will pull that set as soon as we have tested the new set-up and send it to you.  We can at least test this system and see if it provides a better set of metadata to overwrite the older data.

**Comment by lydiam** [comment]
Part 2:  Individual MARCXML file header.

Breaking up the MARCXML files results in individual files that begin with the following:

     <?xml version="1.0" encoding="UTF-8"?>
     <record>
     <header>Some common header Lydia is going to provide </header>
         <leader>01548nam  22003493a 4500</leader>

They should be modified to include the following:

     <?xml version="1.0" encoding="UTF-8"?>
     <record xmlns="http://www.loc.gov/MARC21/slim" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:marc="http://www.loc.gov/MARC21/slim" xmlns:flvc="info:flvc/manifest/v1" xsi:schemaLocation="http://www.loc.gov/MARC21/slim http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd">
     <leader>01548nam  22003493a 4500</leader>

Note:  the line containing <record> is removed because it's included in the second line.

**Comment by lydiam** [comment]
Future development needs to include the following components:
* moving the MARCXML file into the Islandora package and renaming it to marc.xml
* transformation of the MARCXML files to MODS prior to loading via the package program.  This will need some IID work, either in a transformation file or a program, so that the package name = MODS file name = a single IID in the MODS file.
* the MARCXML 852 field seems to get lost in the transformation.  See the MARCXML and MODS in sample https://islandora-test.digital.flvc.org/islandora/object/uf:251

**Comment by lydiam** [comment]
Still waiting for UF to send a new MARCXML file.

**Comment by lydiam** [comment]
UF sent a replacement file.  It's been saved to O:\Digital Services\Islandora\UF DigiTool\MARC replacements.

**Comment by liangzhong** [comment]
1 split the newly come-in marc_report.xml (UF provided)
2 match the individual records against d2i converted packages of "palmm collection" from digitool exported, which Lydia is going to provided.
3 convert each individual marc xml from marc_reported.xml that have match in step 2 to mods xml, i.e. new mods xml file.
4 extract digitool pid and purl information from the corresponding old mods from d2i, insert digitool pid as digitool identifier and purl into new mods.
5 form new package with new mods xml file, uf sobec marc.xml (from marc_report.xml) and rest of files(manefist.xml, stream files) for islandora load.

**Comment by lydiam** [comment]
Liang,
This is a project related to the UF Sobek MARCXML records:  Daniel Cromwell has provided a file of MARCXML records from the Aleph DLU01 library for UNF and FAMU Islandora records in the FHP collection.  The file can be found at /ssa/d2i/dlu01_marcxml/dlu01_recs2.marc-xml.  Each individual record (delineated by the XML record element) needs to be output into its own file.  This is a first step in the project to transform these records into MODS XML and replace them in the appropriate Islandora objects.
