### ISSUE TITLE
advanced search - metadata search and browse

### ISSUE THREAD

**Issue by glewisorg** [FLVC/flvc#14]
I did a little bit of work making this less confusing (I hope).  The autocomplete for metadata browse and search was bringing up all types of Solr fields and the user had to select the correct type for what they were doing.

Now on dev, the autocomplete for metadata browse only lists string type Solr fields.  The browse is like facets and only works with type string.  I also added a checkbox for ignoring case.

The autocomplete for metadata search only lists text type fields.

**Comment by mdemers** [comment]
It's definitely less confusing without the variety of suffixes on the fields but the autocomplete still does not show up for any users who aren't administrators. If the intention is to have them use the autocomplete help find the Solr fields we'll need to get that working as well.

**Comment by glewisorg** [comment]
I changed the access to ISLANDORA_METADATA_EDIT.  We can switch it to something broader if needed.

**Comment by mdemers** [comment]
That fixed it. Is this something easily changed anywhere autocomplete is used, such as formbuilder?

**Comment by glewisorg** [comment]
Each autocomplete has its own access arguments.  If you find the right one, it's not hard to change.

**Comment by glewisorg** [comment]
I tried switching the autocomplete pulldown to a new format like "mods/titleInfo/title" but the "/" character and autocomplete do not work well together and I could not find a simple solution.  For now, I've switched it to using periods like "mods.titleInfo.title" but am open to other suggestions.  I could change it to "<mods><titleInfo><title>" but then you have to type angle brackets to specify multiple elements.

**Comment by glewisorg** [comment]
The markup vanished.  The last sentence was:

 I could change it to  "< mods >< titleInfo >< title >" (ignore spaces) but then you have to type angle brackets to specify multiple elements.

**Comment by lydiam** [comment]
I like the periods between the elements:  it’s a clean display and it seems logical.  I think we can demo it for ISG tomorrow.

The Google analytics are appearing with an overlap during searches, which is odd.  Where – ultimately – were you going to put these?

[cid:image001.png@01D054D8.F277C8F0]

Lydia

**Comment by glewisorg** [comment]
I'm not sure what you mean by overlap.  The views are displaying at the bottom right now, though it seems like not all of them for searches.

I'm going to see what I can do from the flvc module.  My first preference would be to move the views into what is currently displayed in Reports->Google Analytics Summary but that's controlled by a separate module so I don't know if it's possible.  My next preference would be to add another report link to Reports, hopefully under the Google Analytics Summary link, something like Google Analytics Reports.  I'd thought about adding it as a menu item, but the menu is running out of room.

**Comment by glewisorg** [comment]
I opened up a separate issue for google analytics.  You shouldn't see anything under searches now.

**Comment by glewisorg** [comment]
Metadata search and browse is enabled on the advanced search page on all production sites, only visible to roles authenticated user and administrator.
