### ISSUE TITLE
Inventory reports - object counts via Solr

### ISSUE THREAD

**Issue by glewisorg** [FLVC/flvc#15]
On dev, I set up a new Report tab on collection objects to test out the idea of using Solr searches to generate reports.  The tab is visible if logged in, on the same level as IP Embargo and Manage tabs.

The "Generate Report" button generates a report of object counts by content model from the collection you are at, and down through any child collections under that collection.

Each row shows counts of objects directly under each collection.  Counts do not currently include children of book, newspaper, or serial objects (issue, page, and serial pdf objects).  Those counts could either be added to the collection level report, or you might want a separate report tab on the book, newspaper, and root serial objects to generate their child object counts.

There are some optional fields to limit the report.

"Created from date" and "Created to date" limit using the internal Fedora createdDate value.  You can specify either date or both.

"search Solr field" can limit the report by any indexed field.  For example, type "owner" in the first box and select "fgs_ownerId_mt".  Then type "lydia" in the second box.  The report will show counts of objects with ownerId containing "lydia".

Right now, the optional fields don't apply to one report column, the collection content model count, as it doesn't come from Solr.  I would need to adjust the indexing to fix that.

**Comment by lydiam** [comment]
I like it.  I was able to copy/paste the entire report into an Excel spreadsheet without any trouble.

The “owner” search for lydia seemed to retrieve objects in bryan-test, which are owned by Bryan, so I wonder if that’s working correctly.

Can you think of any way that we can make Solr field names more intuitive?  We can create a document that lists the mapping of each Solr field, but that could be cumbersome.  What do you think?



Lydia

**Comment by glewisorg** [comment]
The count in bryan-test is the collection content model count.  Right now, I get the collection content model count from the resource index, so that is the one column unaffected by the optional fields.  I need to remove the gsearch configuration I added a while ago that excludes collection objects from the Solr index, and instead exclude them from searches like we do some of the other content models.

If the "_" and "/" characters are not used in MODS element names, I could change the autocomplete to display the Solr fields differently, like instead of "mods_titleInfo_title_mt", display "mods/titleInfo/title".  And instead of "fgs_ownerId_mt", display "fedora/ownerId".  Then when a field is selected, map it back to the actual Solr field name.  Would something like that be clearer?

**Comment by lydiam** [comment]
That’s much clearer to me, and we could ask ISG.

Lydia

**Comment by glewisorg** [comment]
The optional fields now apply to all columns.  I've adjusted the indexing on dev to index collection objects so they are counted via Solr rather than the resource index.  

One possible problem with using Solr for counts is that Gsearch only indexes objects with state=Active, so it only counts active objects, not inactive or deleted.

**Comment by glewisorg** [comment]
This has moved to production.  Counts for the collection object column will be zero until I adjust the indexing in production.

**Comment by wrandtkeflvc** [comment]
This reports tab was rolled out to users in Spring 2017.
