### ISSUE TITLE
Ingestion errors

### ISSUE THREAD

**Issue by bryjbrown** [FLVC/flvc#16]
Valid and correct MODS records are being rejected during ingest, resulting in the message "Metadata has no owningInstitution" and leaving behind only the title elements in the record.

I've narrowed it down to two specific causes:
1. MODS records containing all prefixed MODS elements, such as `<mods:name>` as opposed to `<name>`
2. Multiple `<extension>` elements.

I've created three zips containing identical metadata but formatted differently to illustrate these errors. [goodbatch.zip](https://dl.dropboxusercontent.com/u/50125925/tmp/goodbatch.zip) contains a PDF and XML file (single extension and unprefixed) which results in [this object](https://fsu-test.digital.flvc.org/islandora/object/fsu%3A7041/datastream/MODS/view#overlay-context=islandora/object/fsu%253A7039). 

[badbatch-prefixed.zip](https://dl.dropboxusercontent.com/u/50125925/tmp/badbatch-prefixed.zip) is identical, except for that its XML file has `mods:` prefixes on every MODS element and results in [this object](https://fsu-test.digital.flvc.org/islandora/object/fsu%3A7042/datastream/MODS/view#overlay-context=islandora/object/fsu%253A7039). 

[badbatch-2extensions.zip](https://dl.dropboxusercontent.com/u/50125925/tmp/badbatch-2extensions.zip) is also identical to the MODS record in [goodbatch.zip](https://dl.dropboxusercontent.com/u/50125925/tmp/goodbatch.zip) except for that it has two separate `<extension>` elements (this element is repeatable according to LOC, and it is considered a best practice to separate semantically different extensions into separate elemements, which I did to differentiate between the `etd:` and `flvc:` elements). It results in [this object](https://fsu-test.digital.flvc.org/islandora/object/fsu%3A7043/datastream/MODS/view#overlay-context=islandora/object/fsu%253A7039).

**Comment by glewisorg** [comment]
badbatch-2extensions.zip has mods prefixes in the xml file.  Can you provide a new example zip file for multiple extension elements with no mods prefixes?

**Comment by bryjbrown** [comment]
Whoops, you're right. Fixed and still at [badbatch-2extensions.zip](https://dl.dropboxusercontent.com/u/50125925/tmp/badbatch-2extensions.zip), but still causing problems [like this](https://fsu-test.digital.flvc.org/islandora/object/fsu%3A7044/datastream/MODS/view#overlay-context=islandora/object/fsu%253A7044).

**Comment by glewisorg** [comment]
The code has been updated on dev and test to handle repeating extension elements.

The mods prefix issue is a little more involved.  In the past, we have had problems with the Full Description being empty when there is a mods prefix is on each element.  At the time, it was decided that incoming MODS XML should never have prefixes on each element.

Looking into it more now, islandoratheme uses SimpleXML to access mods elements.  My validation code in importer (and also the PURL update code) also uses SimpleXML.  You have to use SimpleXML in different ways to access elements that are prefixed vs non-prefixed.

I could figure out how to get the importer validation to handle both, but you still have the problem of the islandoratheme code expecting non-prefixed XML.

Gail
