### ISSUE TITLE
ToC editing on UCF

### ISSUE THREAD

**Issue by mdemers** [FLVC/flvc#18]
About 20 UCF books with duplicate pages will need a table of contents fix. 

Packages can be found on /ssa/d2i/ucf_dups

Spreadsheet detailing what pages are duplicated: https://docs.google.com/spreadsheets/d/1XTa2qZHs1Jq2YIwkdCn4GZa9-hf0IpCm2ubC4MHsQqc/edit#gid=22046572

I think Gail has a script that re-sequences the toc datastream that Randy needs. Would someone fill in the details about what we're looking at trying for this?

**Comment by lydiam** [comment]
These will be dealt with in the context of fixing the book load.
