### ISSUE TITLE
Moving serial intermediates to other serial objects

### ISSUE THREAD

**Issue by mdemers** [FLVC/flvc#22]
Just doing some record-keeping.

Joanne requested that the 2.5 years of The Atlantic Sun be moved into a separate serial root object, The Independent Atlantic Sun. https://fau.digital.flvc.org/islandora/object/fau%3Adtvola

Gail made changes to the RELS-EXT (isMemberof) of these objects but this did not move the objects. Changes did not update the resource index. No solution yet.

**Comment by glewisorg** [comment]
I created a drush script flvc_change_parent that lets you change the parent of an object.  You can try it out on dev.  It's very basic and will let you create relationships that you shouldn't, so be careful when using it.  I was able to move an intermediate serial object from one serial to another (identical serial levels defined).

Options:
 --object                                  The PID of the object to change. Required.                                 
 --parent                                  The PID of the target parent object. Required.                                    
 --parent_relationship_pred                The predicate of the relationship to the parent. Defaults to "isMemberOf".

Example usage:

cd /usr/share/drupal7/sites/islandora7d.fcla.edu
drush flvc_change_parent --object=islandora:4368 --parent=islandora:5128 --parent_relationship_pred=isMemberOf

**Comment by glewisorg** [comment]
Changing the example usage a little bit:

cd /usr/share/drupal7/sites/islandora7d.fcla.edu
drush -v -u 1 flvc_change_parent --object=islandora:4368 --parent=islandora:5128 --parent_relationship_pred=isMemberOf

**Comment by mdemers** [comment]
Finally had a chance to test this out and it works just fine for me. No problems unless I intentionally put an intermediate serial object in a level it doesn't belong in. Even then it only threw up an error message when the tree was displayed instead of blowing up the site. I haven't tried it out with any other content models. Will changing the parent relationship predicate to isComponentOf allow you to change the parent of the PDF objects within serials? Could this allow you to move standard PDF objects in and out of serials?

I'd try it myself but you explicitly said to "be careful" with this one...
