### ISSUE TITLE
google analytics - views of data

### ISSUE THREAD

**Issue by glewisorg** [FLVC/flvc#25]
On dev, there are now two links under Reports related to google analytics.  One is a default summary.  The second link shows views of the data - currently top searches and top facet searches.  The display of views is generated from the flvc module and we can configure it for more views later.

Reports->Google Analytics Summary
Reports->Google Analytics Views

Additionally, there is an object view count displayed at the bottom when an object is viewed.  This count is specific to the object and only displays if the count is greater than zero.

Statistics do not include activity from the current day.  Also, because of limitations on how many times reports can be requested per day and these requests are all tied to a single google user, it is recommended that we locally configure a 3-day cache on the reports.  On dev, I set it to a 1-day cache.

These modules use OAuth 1.0 and a deprecated Google Chart tool.  Google will shutdown use of both in April 2015.  I am monitoring development of the google_analytics_reports module for a new beta release to correct these issues.

**Comment by lydiam** [comment]
I don't see the links on islandora7d.digital.flvc.org - are they in a different development site?

**Comment by glewisorg** [comment]
http://islandora7d.fcla.edu/admin/reports/

**Comment by glewisorg** [comment]
You're right, site admin can't see the Reports link at the top.  We'll have to add another menu item.

**Comment by glewisorg** [comment]
I added the one we control as a menu item.  The summary is from a different module that will hopefully soon be updated, so I don't want to mess with the code there yet.  I can try to pull the summary into our view instead.
