### ISSUE TITLE
ffmpeg on a separate server for video processing

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#28]
Investigate running ffmpeg on a separate server for video processing.  Who should be assigned to this?

**Comment by grf** [comment]
Using AWS as transcoding service and the 212 video set from last video code experiments as an example.

For the sample of 212 videos I used for the last data set,  I collected
video information from the OBJ file streams.

I needed the following information:

* the resolution of the images (HD video, i.e. greater than 720 lines is priced higher than SD video)
* the size of the OBJ datastreams (for transfer and storage cots)
* the duration of the videos,  for which I used the command:  `ffprobe -v error -select_streams v:0  -show_entries stream=height:stream=width:stream=duration  /data/datastreamStore/....`

I've copied my spread sheet data to:

https://docs.google.com/spreadsheets/d/1KTufLiyUeIYoYsnR49lZUhjI69Bt79m4CG20FuJjH-Y/edit?usp=sharing

I used the pricing listed at  AWS as of 2015-03-17 from

 *  http://aws.amazon.com/elastictranscoder/pricing/
 *  http://aws.amazon.com/s3/pricing/



Scenario 1:   Upload data to S3 - and leave it there, serving video to our website end-users

* costs nothing to upload
* transcode (for our 212 examples, this is $17.78)
* store originals (OBJ) at $0.030/GB per month (for our 212 examples, this is $0.27/month or $3.33/year)
* store transcodes (MP4) assume 70% reduction in size, this is $0.19/month or $2.33/year)
* serve video: hard to compute - depends on end users, but negligible.  $0.004 per 10,000 requests.

Scenario 2:  Upload data to S3 - transcode - and retrieve, deleting the original.

* costs nothing to upload
* transcode (for our 212 examples, this is again $17.78)
* store originals (OBJ) at $0.030/GB assume we get charged one month, this is $0.27)
* store transcodes (MP4) assume 70% reduction in size and we get charged one month, this is $0.19)
* retrieve transcodes assumes we're transfering < 10TB and > 1GB, our charge is $0.832.
* delete - no charge

Total for this batch of 212 videos: $19.07.  Or less than half an hour of a programmer's time.

**Comment by grf** [comment]
Dallas and Bill point out I may have underestimated the retrieval costs - the 'requests' needs an estimate of data transferred as well.

They are probably correct.

Then the 'serve video' for 10,000 requests should be reworked.  That would then be roughly 44 MB per request.

(31.28 MB-transfered/request) * (10,000 requests) * (0.090 $/GB-transferred) / (1024 GB/MB)
Or $27.49 plus the $0.004 cents listed previously - call it $27.50

Now that's for 10,000 requests - I doubt we'll ever do that in a month (Lydia: homework exercise - what's digitool been serving up video-wise on average?)

---

Note: the 30.8 MB/request was computed by taking the total size of our videos (9472.667 MB), multiplying  by 0.70 (our transcoded videos have been averaging that size of the submitted videos) dividing by the total number of videos (212).

**Comment by lydiam** [comment]
I don’t believe that we have any current DigiTool usage reports, but the data is stored in individual DigiTool records.  I can probably only come up with some anectodal stats.  Just looking at an FAU “Dances we Dance” record in DigiTool, it’s had 26 views and that includes staff views.  So maybe 15-20 max outside views.  If SCF is going to have students view their dental videos then the stats would be much higher.



Lydia

**Comment by grf** [comment]
Next up:  checking codem,  which has two parts: the first is on or more transcoder webservices, written in node.js.   This scales out "horizontally".   The second part is a scheduler, which keeps track of transcoding hosts. The scheduler is written in ruby on rails (version 4.x) and has a decent management dashboard.

islandora would talk to the scheduler,  which will assign a transcoder service to create a thumbnail and MP4 derivative.  It also accepts a URL and email address, which are contacted when the process completes.

Disadvantages:  files have to get moved around a lot, or shared on NFS-mounted directories.

**Comment by grf** [comment]
Addendum to AWS storage - long term preservation:

Glacier costs are $0.01/GB monthly and $0.05 per 1,000 put/get requests.  It's expected that there are very few requests, and very few deletes. 

These charges are for US West, a different datacenter ("zone") than the S3 storage.

* (9472.66784477234 MB) * (1/1024 GB/MB)  = 9.25 GB
* So for our 212 video examples, that's $0.14 for the first month, $0.09 thereafter.
*  http://aws.amazon.com/glacier/pricing/
