### ISSUE TITLE
IID character validation

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#31]
IIDs are used in creation of Islandora PURLs, and characters invalid in URIs create invalid PURLs.

**Comment by glewisorg** [comment]
Valid IID characters are alphanumeric, underscore, hyphen, period, or parentheses.  All other characters, including spaces, will generate an error.

For forms, an error message displays following the form submit, listing the IIDs with invalid characters.

For zip import, an error message displays and a dummy MODS is created with title only.

Randy was going to handle adding validation to offline ingest.

**Comment by grf** [comment]
On Tue, Mar 17, 2015 at 11:34 AM, glewisorg <notifications@github.com>
wrote:

> Randy was going to handle adding validation to offline ingest.


Handled,  to production pending test.

**Comment by lydiam** [comment]
Is this code on islandload-tst as well?  Is it used by offline ingest?  Can you provide a few more details?
