### ISSUE TITLE
MODS form: Physical location cannot be longer than 128 characters but is currently 154 characters long.

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#34]
In attempting to save a UWF record migrated from digitool the form gives me the following error:  Physical location cannot be longer than 128 characters but is currently 154 characters long.

The exact object is: https://uwf.digital.flvc.org/islandora/object/uwf:35932

**Comment by mdemers** [comment]
I don't see a maxlength value for that field in either of the forms. I wonder if there's a default or there's a character limit set elsewhere. I can try setting the maxlength higher than 154 and see if that setting overrides whatever is creating this limitation.

**Comment by mdemers** [comment]
Boosted maxlength for this field to 200 in MODS Simple Entry in UWF prod. I'll close this issue once it's added to all forms.
