### ISSUE TITLE
Improve derivative quality

### ISSUE THREAD

**Issue by bryjbrown** [FLVC/flvc#35]
Islandora seems be generating pretty low quality derivative images by default. Is there any way we can improve their image quality?

The problem is especially noticeable on the thumbnail/preview datastreams for Scholar objects (citation/thesis content models).

**Comment by grf** [comment]
On Fri, Apr 3, 2015 at 2:49 PM, Bryan J. Brown <notifications@github.com>
wrote:

> Islandora seems be generating pretty low quality derivative images by
> default. Is there any way we can improve their image quality?
>
> The problem is especially noticeable on the thumbnail/preview datastreams
> for Scholar objects (citation/thesis content models).
>

Yes,  give me a pointer to examples and I'll show you alternatives.  There
was a bit of a thread on this last week (buried in an 'oh by the way...')

Gail,  is it possible to use hooks to over-ride embedded commands such as:

      $tn_creation = "$ffmpeg_executable -itsoffset -2 -ss $output_time -i
$archival_path -vcodec mjpeg -vframes 1 -an -f rawvideo $out_file";

in video/includes/derivatives?

There are others as well.

**Comment by bryjbrown** [comment]
> Yes,  give me a pointer to examples and I'll show you alternatives.

Sure, http://fsu-test.digital.flvc.org/islandora/object/fsu%3A7532
Its a thesis object that prominently features the PREVIEW datastream which is pretty grainy.

Bonus question: If we DO up the quality on derivatives, is there an easy way to regenerate ALL the derivatives for a certain content type? I'd prefer not to have to reload all 886 theses.

**Comment by grf** [comment]
Using the command:

   convert -quiet -resize 500x700 -density 600  -colorspace RGB
scholar-example.pdf'[0]'  scholar-example-preview.jpg
   convert -quiet -resize 200x200 -density 600  -colorspace RGB
scholar-example.pdf'[0]'  scholar-example-thumb.jpg

Gives me the attached images.   Significantly better.

Waiting for Gail to weigh in on the best way to go here,  to use the above
kinds of commands.

Pretty easy to update as well.

1) use an RI query to find all object PIDs of the content model you are
interested in

then for each PID

2) use curl to download PDF datastream for given PID (or use
where-are-datastream to find them on the web server)
3) use above commands to generate PREVIEW, THUMB
4) use offline-ingest/tools/update-datastream object-pid datastream-name
new-datastream-filename


A bit of shell scripting once you've gotten #1.

and Bob's you uncle.

**Comment by glewisorg** [comment]
This is the bit of code that generates the command:

function islandora_pdf_create_jpg_derivative($file_uri, $dsid, $width, $height) {
  $source = drupal_realpath($file_uri) . '[0]';
  $matches = array();
  // Get the base name of the source file.
  $base = pathinfo($source, PATHINFO_FILENAME);
  $temp = file_create_filename("$base.$dsid.jpg", 'temporary://');
  $dest = drupal_realpath($temp);
  $args['quality'] = '-quality ' . escapeshellarg(variable_get('imagemagick_quality', 75));
  $args['previewsize'] = '-resize ' . escapeshellarg("{$width}x{$height}");
  $args['colors'] = '-colorspace RGB';
  $args['flatten'] = '-flatten';
  $context = array(
    'source' => $source,
    'destination' => $dest,
  );
  drupal_alter('imagemagick_arguments', $args, $context);
  // To make use of ImageMagick 6's parenthetical command grouping we need to
  // make the $source image the first parameter and $dest the last.
  // See http://www.imagemagick.org/Usage/basics/#cmdline
  $command = escapeshellarg($source) . ' ' . implode(' ', $args) . ' ' . escapeshellarg("jpg:$dest");
  $output = '';
  $ret = -1;
  if (_imagemagick_convert_exec($command, $output, $ret) !== TRUE) {
...

--------
There's a drupal_alter call in there, which passes variables to hook_imagemagick_arguments_alter.  There is an existing function for this hook in imagemagick/imagemagick_advanced/imagemagick_advanced.module:

function imagemagick_advanced_imagemagick_arguments_alter(&$args, $context) {
  // Change image density.
  if ($density = (int) variable_get('imagemagick_advanced_density', 0)) {
    $args['density'] = "-density {$density} -units PixelsPerInch";
  }
...

where $density is either 0 or 72.  This corresponds to the checkbox in the ImageMagick configuration:

Change image resolution to 72 ppi
Resamples the image density to a resolution of 72 pixels per inch, the default for web images. Does not affect the pixel size or quality.

--------
 hook_imagemagick_arguments_alter is called from islandora_ocr, islandora_scholar, islandora_solution_pack_large_image, and islandora_solution_pack_pdf.  I would guess that adding this hook to the flvc module would affect JPGs for all of these modules.  Likewise, checking the 72 ppi checkbox would affect all of these modules.  Do we want to isolate these changes to PDF only?

Gail

**Comment by grf** [comment]
On Mon, Apr 6, 2015 at 2:49 PM, glewisorg <notifications@github.com> wrote:

> hook_imagemagick_arguments_alter is called from islandora_ocr,
> islandora_scholar, islandora_solution_pack_large_image, and
> islandora_solution_pack_pdf. I would guess that adding this hook to the
> flvc module would affect JPGs for all of these modules. Likewise, checking
> the 72 ppi checkbox would affect all of these modules. Do we want to
> isolate these changes to PDF only?
>
>
Well,  I know we want to use -density for PDFs -

*This option specifies the image resolution to store while encoding a
raster image or the canvas resolution while rendering (reading) vector
formats such as Postscript, PDF, WMF, and SVG into a raster image. Image
resolution provides the unit of measure to apply when rendering to an
output device or raster image. The default unit of measure is in dots per
inch (DPI).*
 -http://www.imagemagick.org/script/command-line-options.php?#density

I don't think that the 72 DPI setting makes much difference for us,  since
we specify the absolute sizes of the derived images (if we were specifying
inches, say, then it would be used in scaling).
