### ISSUE TITLE
Retrieval of newspaper and serials issues in simple search

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#40]
Currently simple search doesn't retrieve newspaper and serials issues (nor does it retrieve children of Compound Objects).  However, "Advanced Search" Metadata Only will retrieve issues.

Because FLVC is using empty simple searches to produce "view all" search results, we exclude objects that are not title-level from simple search, like newspaper issues, newspaper pages, book pages, etc.  A simple search for "amara" gets no hits because newspaper issue objects are excluded.

Gail suggested that we change the behavior depending on whether the simple search is an empty search or not.

empty search - exclude objects that are not title-level
query search - include additional child objects, such as newspaper issues, serial issues.

This issue will be pursued at the next ISG meeting.

**Comment by lydiam** [comment]
ISG approved the enhancement on 8/25/2015.  Please go ahead with the coding.

**Comment by glewisorg** [comment]
I think I've got this done on dev.  Let me know if it's ready for test.

**Comment by lydiam** [comment]
It seems to work in Dev for newspaper issues.  I'll test a serials issue as well before I sign off on putting this into test.

**Comment by lydiam** [comment]
Testing with serials issues I'm finding that metadata from "child" PDF objects are not being retrieved in simple search, but the "intermediate objects/intermediateCModel objects are being retrieved.  That works fine when the intermediate object is an issue that has article-level PDF children, but it doesn't work in cases where the intermediate object is just a tree "node" with very little metadata and the issue-level metadata resides in it's child PDF issue object.  See object http://islandora7d.fcla.edu/islandora/object/islandora%3A4322.  It's child is http://islandora7d.fcla.edu/islandora/object/islandora%3A4331, which is a PDF.  You want to retrieve on metadata in the PDF and not it's intermediate object in this case because this is an issue-level PDF.   

I think it's OK to retrieve on serials PDF child object metadata in addition to intermediate object metadata, because that will enable users to retrieve both issue metadata and article metadata.

**Comment by glewisorg** [comment]
On dev, serial PDFs should now be included in non-empty simple search.

**Comment by lydiam** [comment]
That appears to be working.  I haven't tested article-level metadata retrieval, but this is good enough to be sent to the test server for further testing.  

A few observations:  
1. Searching on serial titles will now often retrieve the serial title record and all of its issues, because title information is repeated in issue metadata.  
2. Serials issues appear in the format facet as PDFs and serial title objects as "Serial".

**Comment by glewisorg** [comment]
The changes to simple search have been moved to test.

**Comment by lydiam** [comment]
This is perhaps a weakness overall in the serials display in cases where there are article-level PDFs:  the Full Description tab displays metadata for the *article* and the Serial Details tab displays metadata for the serial title, but there's no tab to display metadata for the entire issue.  This is not a big problem when you view the serial entering from the serial title/tree, but it's more problematic when you retrieve an article via simple search.

When retrieving an article-level PDF via simple search, the search results display the article title and thumbnail (good).  (e.g., in islandora-test search for "curtis moore")

However, when you click on the article itself the only indication of issue-level metadata and the only ways to get to the list of articles in that issue are either to click on the breadcrumb for the issue, or to go back to the tree via the "All Issues" link.  When you access the issue via the tree or issue breadcrumb you're presented with a Summary tab that lists all articles, a Full Description tab that provides issue-level descriptive metadata, and a Serial Details tab that provides serial title-level metadata.

So getting from an article retrieved via simple search to issue metadata is awkward.  I have no immediate solution to the problem.  On the other hand, the ability to retrieve articles via simple search I believe is a great enhancement.

**Comment by lydiam** [comment]
In cases where there is metadata only at the issue level and article-level PDFs, simple searches that retrieve issue metadata display Format "Serial component".  That's acceptable.  Clicking on the "serial component"/issue in search results displays the issue metadata/summary of articles correctly.

**Comment by glewisorg** [comment]
This change moved to production on 9/20/15.
