### ISSUE TITLE
logged in users, when using list view, get an empty screen on the second display page

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#43]
This happens in Firefox, Chrome and IE on my PC,  and Firefox and Chrome on Krystal's MAC so may not be browser related.  The problem was reported by FSU in the following email:

"This has been around for awhile but I couldn’t find that I ever reported it so wanted to do so now. It is only an issue when I’m logged in so not a pressing matter for our public users.

When I am in a collection, I sometimes want the list view over the grid view if I need the dates. When I switch to list view, the first page is fine and displays normally but when I try to go to the second page or beyond, I get this:
 
(image)

This happens in both Firefox and Chrome to me on my Mac. I have not tested it on a PC. I usually solve the issue by going to the public view but I shouldn’t have to so I wanted to report it!"

To reproduce Krystal's example:
- log into fsu.digital.flvc.org
- go to collection:  https://fsu.digital.flvc.org/islandora/object/fsu:historicalnewspapers
- click on List View (note the list view display)
- click "2" or "next" and you just get the page navigation links and no contents.

The related CRM case is CAS-59123-H4B7.

**Comment by glewisorg** [comment]
This was already reported as an issue in islandoratheme:

https://github.com/FLVC/islandoratheme/issues/41

I put a fix in yesterday on dev and test.

**Comment by glewisorg** [comment]
Fix moved to production on 9/29/2015.
