### ISSUE TITLE
Solr indexing for namePart type="given", "family", "termsOf Address", "date"?

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#44]
From: Brown, Bryan [mailto:bjbrown@FSU.EDU] 
Sent: Thursday, October 08, 2015 4:59 PM
To: FLVC-ISLANDORA-DEV@LISTSERV.FLVC.ORG
Subject: [FLVC-ISLANDORADEV] Solr creator name bug

After doing some user testing with faculty members with the beta version of our repository, we noticed a pretty embarrassing mistake: Solr seems to be treating the first name and last name of authors as different authors in search results and facets. See this search results page for an example: https://fsu.digital.flvc.org/islandora/search/?type=edismax&collection=fsu%3Auniversity_libraries 

Notice the first item in the search results says "Micah, Vandegrift, Josh, Bolick". The authors are "Micah Vandegrift" and "Josh Bolick", so it should be displaying "Vandegrift, Micah, Bolick, Josh". If you look at the "Creator" facet at the bottom of the search results page, you'll see that its listing first names and last names separately which really affects the usefulness of these facets. "Micah" and "Vandegrift" are two separate facets as opposed to one "Micah Vandegrift" facet.

I noticed that this isn't the case in other collections, such as the Photographs collection (https://fsu.digital.flvc.org/islandora/search?type=edismax&f[0]=RELS_EXT_isMemberOfCollection_uri_ms%3A%22info%3Afedora/fsu%3Afscwphotosmain%22). You can see here that Solr is indexing the names properly, and returning entire names as search facets (such as "Fox, Grace Imogene").

It looks like this is working in these collections because the MODS records have very simple name elements where the entire name is preformatted in a single <namePart> element, such as:

         <name type="personal">
         <namePart>Price, Dorothy Ina</namePart>
         <role>
         <roleTerm type="text" authority="marcrelator">creator</roleTerm>
         </role>
          </name>

In the repository where the Solr indexing isn't working properly, we have more complex (but proper) MODS naming where author names are separated into "given", "family" and "termsOfAddress" namePart elements (first, last, and suffix), such as:

     <name type="personal" authority="local">
     <namePart type="given">Plato</namePart>
     <namePart type="family">Smith</namePart>
     <namePart type="termsOfAddress">II</namePart>
     <role>
     <roleTerm authority="rda" type="text">author</roleTerm>
     <roleTerm authority="marcrelator" type="code">aut</roleTerm>
     </role>
     </name>

My guess is that Solr and/or GSearch is set up to index a creator from each namePart individually instead of constructing a creator field conditionally (although I've not worked directly with Solr in a while, so I may be way off base). I'm not sure how much of a hassle this would be to format these individual fields into one in the Solr schema, but it would be an important feature going forward since this is the LOC best practice for naming authors in MODS records (http://www.loc.gov/standards/mods/userguide/name.html#namepart).

We'd love to have this fixed before we launch the repository in January. Let me know if you need for me to provide any more examples, I'd happily share the workload on getting this fixed if possible.
-Bryan

**Comment by lydiam** [comment]
Per Gail:

So it looks like the name block has a similar problem.  The steps to resolve would be:

1.  Someone (could be you or Lydia or Mike) tells me exactly what to check for and how to combine the different name elements into a single Solr field.

2.  I struggle with this logic in the Gsearch configuration (in XSLT) to add a new Solr field.

**Comment by bryjbrown** [comment]
The checks should be if there are multiple namePart elements in a single name element or not, and if there is only one namePart, it becomes the entirety of Solr's "Creator" field (current behavior I think).

If there are multiple nameParts in a single name element, then format them based on their @type (which can be "given" (first name), "family" (last name), or "termsOfAddress" (like "III", "Jr.", "Esq.", or "Dr."). 

Unfortunately "termsOfAddress" elements can appear before or after the name (as in "Dr. Bryan Brown" or "Bryan Brown IV") so theres no real way to know how to tell whether they should go in front or not. My vote would be to just not index them, but I'll defer to a higher metadata authority on that.

Assuming we're only worried about "family" and "given" @types of namePart elements, these should get combined into the Solr "Creator" field as "family, given".

**Comment by lydiam** [comment]
It does appear that the parsing should be pretty simple, per http://www.loc.gov/standards/mods/userguide/name.html#namepart:

namePart type=family comma space namePart type=given

See 

"Guidelines for Use

The name itself is always contained in a <namePart> element. MODS allows for either breaking up parts of the name (given and family, for example) in different <namePart> elements or enclosing the entire name in one element. Use of the former method affords more control in sorting and display and should be used if the data is readily available. Either method is acceptable.

For greater interoperability, name elements should appear in the same order as in their authorized form (the authority cited in the <name> authority attribute). If no authority is used for personal names, last name or family name should appear first, followed by a comma, followed by first or given names.

Parsing can be used to indicate a date associated with the name, to parse the parts of a corporate name, or to parse parts of a personal name if desired."

That should be the only way that namePart with type attributes of "family" and "given" is dealt with that's different from namePart with no type attribute.

It would be helpful to document how name and namePart are currently parsed to create Solr fields.  I'm hoping that namePart type="termsOf Address" is already dealt with in Solr field creation, but it would be useful to know for sure.

**Comment by lydiam** [comment]
Gail,

Can I assign this to you?  It relates to the FSU repository, which is going to be made very public on Feb. 29.  I think it's a minor enough adjustment that it doesn't have to go through ISG.  My recollection is that we've made these tweaks in the past on our own.

**Comment by glewisorg** [comment]
The default logic that indexes MODS fields works on an element by element basis and does not take into account rules of MODS for combining elements.  It has no MODS intelligence at all and it cannot be introduced here.  This default configuration produces the current facet fields mods_name_namePart_ms and mods_subject_name_namePart_ms.  We have never tweaked the default logic.

Our approach has been to leave those fields in place and to define new custom Solr fields with our own logic to combine elements, and then use that new field for the facet instead of the one currently used.  For example, we define new fields mods_name_namePart_display_ms and mods_subject_name_namePart_display_ms.  This means we would be starting from scratch to build these fields.  I would need to know what to do for mods->name->namePart and mods->subject->name->namePart for every possible type: no type, date, family, given, and termsOfAddress.  Then I would need to reindex all objects with these elements in the FSU site to generate the new fields before switching the facets to use the new fields for FSU.

**Comment by mrmiguez** [comment]
Hi Gail,

I have a giant python `elif` tree that constructs MODS names according to whatever combination of attributes are present.

It's the first function: nameGen - https://github.com/fsulib/metadataWorkflowResources/blob/master/csv4cat/MODStools.py

Does that help?

-MM

**Comment by glewisorg** [comment]
That's a bit complex.  I have to do this in xsl (Gsearch config).  The simpler it can be done, the better.  This being a facet field, we're thinking it would be okay to exclude type=termsOfAddress and type=date.  Assuming these are all under the same name element, if there is a namePart with no type, and also nameParts with type family or given, should they be indexed separately as

no-type    (indexed by itself, as-is)
family, given

**Comment by mrmiguez** [comment]
That's probably appropriate. @type=date might occasionally be useful for disambiguation. termsOfAddress has no such role. I include as the catalogers want it for their MARC records.

**Comment by aglerum** [comment]
Here is XSLT for inverting MODS names that accounts for both terms of address and dates: [inverted_names_mods.xsl](https://gist.github.com/aglerum/6f6bc32b2912d7e03053.js) I tested it on a sample of 380 names and it seems to be working as expected. 

Hope this helps!

Annie

**Comment by bryjbrown** [comment]
Fixing the link to @aglerum's XSL: https://gist.github.com/aglerum/6f6bc32b2912d7e03053

**Comment by aglerum** [comment]
Thanks for fixing the MD @bryjbrown!

**Comment by glewisorg** [comment]
Thank you for the examples.  I still hesitate to include dates.  If one object has an author with no date and a second object has the same author with type=date included, then those objects would produce separate facet links.

I've configured the test server to create fields mods_name_namePart_display_ms and mods_subject_name_namePart_display_ms with this logic:

no-type (indexed by itself, as-is)
family, given

I reindexed objects on the test server.  For site fsu-test, I added the facets "Name as Subject *new*" and "Creator *new*" for the new fields.  Let me know what you think.

**Comment by bryjbrown** [comment]
@glewisorg I 100% agree about not including dates for the exact same reason (inconsistent use of date generating duplicate facets for the same person). 

The "Creater new" facet looks fantastic, its parsing the names exactly as I would expect to see them in a facet. 

The only thing that I'm noticing on fsu-test now is that there is no "Creator" field in the search results. There used to be, and it was showing the mis-parsed names as "Author1FirstName, Author1LastName, Author2FirstName, Author2LastName". If you can get the new Creator facet to show in the search results as "Author1LastName, Author1FirstName" as it is in the facets, we'll be good to go.

**Comment by glewisorg** [comment]
I added mods_name_namePart_display_ms as Creator to the search results display fields.

**Comment by bryjbrown** [comment]
@glewisorg Awesome. It looks great! Assuming we swap "Creator" with the rules for "Creator new", I'd say this meets all of my requirements. :+1:

**Comment by glewisorg** [comment]
I just swapped out the Creator and Name as Subject facets.  The old ones are now on the bottom, marked as old, for comparison's sake if anyone else wants to check it.  Unless I hear otherwise, I will move the indexing change to production this weekend and start reindexing objects to pick up the new fields.  I will switch the facets for FSU after the reindexing is done.  By what date is this needed?

**Comment by bryjbrown** [comment]
@glewisorg We're going to be having a major PR push and launch party with demos on Feb. 29, so if we can get it looking proper on prod and reindexed by the weekend before I'd be pretty happy.

**Comment by glewisorg** [comment]
Indexing for the new facet fields is nearly complete.  There are two remaining objects that are failing to index properly.  It appears to be an issue with problematic dates that are causing indexing to break.

fsu:121356

`<originInfo><dateIssued encoding="w3cdtf">1929-04-31</dateIssued>`

problem - only 30 days in April.

fsu:116939

`<originInfo><dateCreated>23-12-1930</dateCreated></originInfo>`

problem - format of DD-MM-YYYY not supported.  Change to MM-DD-YYYY.

Let me know when these objects have been fixed and I will recheck the indexing.

**Comment by bryjbrown** [comment]
@glewisorg I updated the MODS datastreams on these records, they both have w3cdtf formatted dates.

**Comment by glewisorg** [comment]
That fixed the indexing.  To compare new vs old facets:

[https://fsu.digital.flvc.org/browse/report?solrfield=mods_name_namePart_display_ms&sort=count&pagesize=1000](url)
vs
[https://fsu.digital.flvc.org/browse/report?solrfield=mods_name_namePart_ms&sort=count&pagesize=1000](url)

and

[https://fsu.digital.flvc.org/browse/report?solrfield=mods_subject_name_namePart_display_ms&sort=count&pagesize=1000](url)
vs
[https://fsu.digital.flvc.org/browse/report?solrfield=mods_subject_name_namePart_ms&sort=count&pagesize=1000](url)

Let me know if you think we're ready to make the switch.  Configuring the facets for FSU shouldn't need to wait until Sunday.  Any time outside of peak hours should be fine.

**Comment by bryjbrown** [comment]
@glewisorg This looks good to me. I don't see any issues, I think we should be ready go.

**Comment by glewisorg** [comment]
Okay, I'll change the facets late tonight.

**Comment by glewisorg** [comment]
Facets were changed last night.  Let me know if you see any problems.

**Comment by bryjbrown** [comment]
@glewisorg The "Creator" facets look great, but the "Creator" field on search results still displays the authors in the old "First, Last" way. Can this be updated as well?

**Comment by glewisorg** [comment]
Done.  Thanks for reminding me.

**Comment by bryjbrown** [comment]
Thanks, @glewisorg. I think we can close this ticket now.

**Comment by glewisorg** [comment]
Indexing change for new name fields moved to production on 2/14/2016.  Reindexing completed for FSU and facets and display fields updated for site.
