### ISSUE TITLE
wmv conversion

### ISSUE THREAD

**Issue by mdemers** [FLVC/flvc#46]
GCSC has wmv files that need to be ingested into Islandora as part of their migration. The video content model does not accept this file format. All ingested video files require an mp4 derivative be created for playback through the jwplayer.  ffmpeg can convert wmv files to mp4 but we need to explore both why this is not one of the accepted formats and the best way to migrate these videos into islandora. 
Do we:
- Provide GCSC format requirements and direction on how to convert the files themselves.
- Convert the files in-house prior to migration.
- Update the video solution pack to include wmv conversion.
- Add video to offline ingest w/inclusion of wmv conversion.
- A better idea.

**Comment by wrandtkeflvc** [comment]
For these videos, the original video in .wmv format was uploaded to Islandora as a Binary Object, then a .mp4 derivative was uploaded as a Video, then a Compound Object was used to tie those two files together.

I'm closing this issue now, since the GCSC migration is complete.
