### ISSUE TITLE
Collection PIDs and namespace restrictions

### ISSUE THREAD

**Issue by wrandtkeflvc** [FLVC/flvc#51]
Right now, it is my understanding that namespace restrictions are enforced on all the Islandora sites.  So, as site can have namespaces of “islandora” or “ir” or “thepartthatcomesinfrontofthe.digital.flvc.orgURL”.

But, right now, a person can create a collection with any namespace at all.  I just made a collection with the namespace "minasnamespace".  Here it is https://floradora.digital.flvc.org/islandora/object/minasnamespace%3Afloradoranamespace .  None of us can get to it, because namespace restrictions are turned on.

Is it possible to do something like this?:  When a person creates a new collection, and enters the PID for that collection, that form checks the namespace restrictions.

**Comment by lydiam** [comment]
With namespace restrictions a site can only use namespaces, case-sensitive, that are listed in the namespace configuration, plus "islandora" and "ir".  Those are the only legitimate namespaces when restrictions are set. The collection MODS form does allow input of any text in the collection PID, but if the namespace in that element doesn't match the restricted list the user will get an "Access denied" error page when an attempt is made to access the newply created object.  The only way to delete that object via the GUI is by temporarily enabling the problem namespace or temporarily turning off restrictions. Both solutions require FLVC intervention. It may be possible to delete the collection object using Randy's delete-by-pid script, but that would also require FLVC intervention.
________________________________

**Comment by wrandtkeflvc** [comment]
Yes, the person enters a not-allowed-namespace, then they click through all the steps to make a collection, then they click "Ingest", then then cannot get to that collection or retrieve it by search.  It feels like they did everything, and then when they push "Ingest" (ie. "Save") their work got deleted.

It would be better to reject the not-allowed-namespace, give an error message on that first screen, and stop them before they click through all the steps.  And, only let them proceed with a correct namespace.

**Comment by wrandtkeflvc** [comment]
Since I posted this issue, it's come up twice more, where users think the ability to create a collection is not working.  The FLIIRT group reported this on the ir-test site, because the ir-test site uses the "ir:" namespace, but users were in the habit of using their institutional namespaces, and so created collections which they could not access.  Valencia College also reported this, and said that there were sometimes problems with creating a collection.

**Comment by lydiam** [comment]
How is Valencia experiencing problems creating new collections?  What are they using for a namespace?  Can you give an example from Valencia's site?  What is the point of confusion?

**Comment by wrandtkeflvc** [comment]
One CRM ticket I handled this week goes back to this issue of Islandora letting people create Collections with PIDS in a namespace that that same person then can't access.  A school created a collection with a not-allowed PID.  On the homepage of Islandora, there's a drop down menu of collection names, and you can search within any collection on the site.  The collection with the not-allowed PID showed up in this drop down menu and they'd written that the drop down menu options were wrong.

If the process of creating a Collection made the person use a PID in an allowable namespace, then that problem wouldn't have occurred.

**Comment by wrandtkeflvc** [comment]
On March 29, 2017, FSU reported this same problem (created a collection in the FSU: namespace instead of fsu: namespace then couldn't delete it).  Bryan reported that to the FLVC Islandora Developers listserv.  This would be prevented by adding validation around the part of creating a Collection where you manually enter a PID.
