### ISSUE TITLE
Why are most queries written in iTQL ~ could I extend to use SOLR?

### ISSUE THREAD

**Issue by wgilling** [FLVC/flvc#52]
Hello -- I am working with the University of Pittsburgh.  It looks like you guys created a pretty great wheel and we would really like to check out this package and how it handles TOC needs for our system.

We recently updated from Mulgara to Blazegraph and the module does not function at all because Blazegraph does not support itqlQuery calls.

We have noticed a lot better performance with Solr queries in our configuration.  I could potentially rewrite parts of the page_alter function that have these itqlQuery calls so that it works with either query language (by getting $results based on the config) - and add a radio selection to the admin section to give a selection for query languages: "iTQL", "Solr".

best regards,
Brian Gillingham
University of Pittsburgh | University Library System

**Comment by glewisorg** [comment]
We will be trying out Blazegraph next month so changing these queries from iTQL to SPARQL has moved to the top of my to do list.  I hadn't considered replacing them with Solr queries.  We're trying to switch to Solr in other modules so it would make sense to try that here.  I likely won't do a config option yet, just replace the queries for now.  I'll add another comment here once I get the module updated.

How is Blazegraph working out for you?

Gail Lewis

**Comment by glewisorg** [comment]
I changed all iTQL queries to SPARQL in this module.  Please let me know if it works with Blazegraph now.

I will have to delay working on the Solr queries part - too many other tasks to finish.  If you decide to give it a try, I would love to see how it turns out.

Gail Lewis
