### ISSUE TITLE
Islandora Entities CSV Import - import can only be run if the username on the account is "admin"

### ISSUE THREAD

**Issue by wrandtkeflvc** [FLVC/flvc#54]
For the Islandora Entities CSV Import, the import can only be run from a user account named "admin".  It would be preferable if the username on the account didn't matter.

This is related to FLIIRT Phase 2.  I've gone through the Islandora Entities CSV Import, and the username of "admin" issue is the only bug.  I also anticipate institutions wanting a way to import thumbnail images along with a batch import, so that might be requested once an institution decides to import using this.

**Comment by glewisorg** [comment]
Wilhelmina, give this a try on ir-dev and let me know if it's allowing other usernames now.

**Comment by wrandtkeflvc** [comment]
This looks good to me on ir-dev .  But also, today, I can batch load from any account on ir-test as well.  Does that mean that the code change is put through on the test sites?

**Comment by glewisorg** [comment]
I did not move my fix to the test server.  The change on the dev server was to set the object owner to the authenticated user's name if available, or 'admin' otherwise.  Before it was setting all object owners to 'admin', which is what test should still be doing.  Was that not the problem?

**Comment by wrandtkeflvc** [comment]
Hmmm... It let me run the batch import on ir-test from my own user account and ran all the way through.  Before, it would start to load the first entity, then error out.

On fgcu-test , it still does the same error.  If I try to do a batch import from the account with my personal username, it loads the first item, but not other rows.  I haven't looked at fau-test nor ucf-test yet.

I wonder if the difference is that I had created an account named "admin" on ir-test ?  I deleted the "admin" username account on ir-test , and the batch load still runs there.  But, maybe a record is kept somewhere in the software.  Like, maybe that allows objects to be owned by that user, but if the user never existed then they can't.  Maybe that's why it's working on ir-test even though your code change isn't in?

**Comment by glewisorg** [comment]
I'm not really sure.  I went ahead and just moved the code to the test server.  Try a batch import in fgcu-test again (as you).

**Comment by glewisorg** [comment]
Wilhelmina, can you check fgcu-test again?  I moved the change to test and want to know if import is working now.

**Comment by wrandtkeflvc** [comment]
Yes, this batch loading scholar entities from the csv file is working on fgcu-test now.
