### ISSUE TITLE
HTML symbol for carriage return not showing in display in "Details" tab

### ISSUE THREAD

**Issue by wrandtkeflvc** [FLVC/flvc#76]
The goal here is to put a line break / paragraph break in text that is stored in an XML field.

It's not OK to put `<br/>` or `<p>` because the angle brackets will read as an XML element and cause a validation error.

The HTML symbol for carriage return is `&#13;`   That works fine with XML and XML will validate.  That's what the Islandora forms store.  But, that's not being displayed correctly to users.

When XML is edited with the MODS forms, and a return is put in, the forms will store that return as `&#13;`
But, then when someone comes over and looks at the object and clicks to the "Full Description" tab, the return doesn't show up.  It's just a big huge block of text.  I think this is for all content models.

It looks like what is happening is:
The MODS XML is stored with the `&#13;` in it.
Islandora generates the display and when it generates the display, it replaces the `&#13;` with whitespace.
The browser shows all white space as a single space because that's how whitespace displays in HTML.

I think that what has to happen is that when Islandora generates the HTML from the XML that it should leave the `&#13;` in there.

Here's an object on dev (line breaks in the note field):
https://islandora-dev.digital.flvc.org/islandora/object/dev%3A1303

Here's an object on test (line breaks in the note field):
https://fscj-test.digital.flvc.org/islandora/object/fscj%3A995

Here's an object on production (line breaks in the note field):
https://floradora.digital.flvc.org/islandora/object/floradora%3A1206

**Comment by bryjbrown** [comment]
@wrandtkeflvc One thing that does work (although its a bit cumbersome to type) is to use entity references. You are certainly correct that having a `<br/>` or `<p>` nested inside MODS would make it invalid, but having a `&lt;br/&gt;` or `&lt;p&gt;` is perfectly fine, and Drupal (usually) automatically encodes it into true HTML tags before the browser sees it. Give it a shot and see if it solves your use case, I've done this a few times before in MODS `<abstract>` fields where line breaks were necessary.

**Comment by wrandtkeflvc** [comment]
Thanks Bryan.

For the specific context this came up in (a template on a MODS form), I can change the text encoding in the template.

With  someone can correctly encode the XML with `&#13;` but Drupal won't show the whitespace.

I guess I'll poke around whether it's worth a Jira ticket or not.  Text encoding is "quirky" in all these little details.
