### ISSUE TITLE
FAU Broward Legacy migration of article-level PDFs

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#9]
For discussion to determine if this warrants programming:

FAU has 58 issues of Broward Legacy both in DigiTool and OJS.  In both they have article-level PDFs, but in DigiTool the METS has only article title metadata while in OJS the exported METS has article title and author metadata.

Ideally these issues would be migrated to Islandora with article-level nodes and metadata.  

Question:  how much work would it be to use to use either DigiTool issues and/or OJS issues as input for a program that would do something along the lines of the following:
• Create good issue-level MODS that would probably have to be manually loaded for each of the 58 issues (I think that metadata could come from DigiTool for the most part) (DONE in fau7prod)
• For each article issue, probably from OJS, create one MODS file with article author/title info, naming the MODS file with the same extension as the PDF for zip loading

Those are really broad strokes, but I have a few exported OJS files on 0:\Digital Services\Islandora\FAU\Broward Legacy OJS  and DigiTool issue-level MODS files on 0:\Digital Services\Islandora\Serials\FAU-FHP_serials\Broward Legacy\issue_MODS.

For me creating the article-level zip files would be a fair amount of work.

**Comment by lydiam** [comment]
Gail is looking at this.

**Comment by glewisorg** [comment]
• Create good issue-level MODS that would probably have to be manually loaded for each of the 58 issues (I think that metadata could come from DigiTool for the most part) (DONE in fau7prod)

I don't think there's any coding to be done for issue level MODS.  Your examples of DigiTool issue level MODS look okay to me.  Are they missing something?  Those would have to be added manually.

• For each article issue, probably from OJS, create one MODS file with article author/title info, naming the MODS file with the same extension as the PDF for zip loading

We could code something to create the individual PDF level MODS files from each OJS METS file.  Would it be okay to just grab each article MODS block, drop in the flvc extension, and write it to a file without parsing for author/title info?  That would be faster to code.

**Comment by lydiam** [comment]
Gail,

Your suggestion for the following would be a help, although then someone would still need to update the MODS to grab author/title info from the METS and include it in the MODS.  But that part of the work would not be more than we do manually to fix DigiTool books and we might be able to hand it off to Chris Carney or even Debra.

We'd need to clarify the naming conventions for the article-level MODS files - how will we know which MODS file goes with which article if it doesn't contain an author or title?

**Comment by lydiam** [comment]
Each MODS block in METS file contains a PDF identifier and would have a unique ID for each PDF.

I'll take another look to see if there's an easy way to get the author/title.

**Comment by lydiam** [comment]
Gail,

This is what I see in the METS from OJS:

1 - article-level divs in the structMap like this (there are section-level divs, but we can enter those manually):

     <METS:div TYPE="article" DMDID="A-82234">
     <METS:fptr FILEID="F96686-A82234"/></METS:div>

2 - dmdSecs whose IDs are the DMDID in the article div: 

DMDID in this case refers to the following dmdSec:

     <METS:dmdSec ID="A-82234">
     <METS:mdWrap MDTYPE="MODS">
     <METS:xmlData><mods:mods>
     <mods:titleInfo><mods:title>Table of Contents</mods:title></mods:titleInfo>
     <mods:abstract><p> </p><p> </p><p> </p><p> </p></mods:abstract>
     <mods:name type="personal"><mods:namePart type="given">Broward County Historical</mods:namePart>
     <mods:namePart type="family">Commission</mods:namePart><mods:role>
     <mods:roleTerm type="text">author</mods:roleTerm></mods:role></mods:name>
         <mods:genre>article</mods:genre><mods:originInfo>   <mods:dateIssued>2013-06-22EDT10:07:21-04:00</mods:dateIssued>
   </mods:originInfo>
<mods:language>en</mods:language></mods:mods></METS:xmlData></METS:mdWrap>  
     </METS:dmdSec>

(in this case the MODS is pretty bad)

We'd use the following bits of the MODS, but it might not hurt to grab the entire dmdSec:
     <mods:titleInfo><mods:title>Table of Contents</mods:title></mods:titleInfo>
     <mods:name type="personal"><mods:namePart type="given">Broward County Historical</mods:namePart>
     <mods:namePart type="family">Commission</mods:namePart><mods:role>
     <mods:roleTerm type="text">author</mods:roleTerm></mods:role></mods:name>

3 - A fileSec file whose ID matches the structMap's FILEID.  In this example:

  <METS:fileSec>
   <METS:fileGrp USE="original">
   <METS:file ID="F96686-A82234" SIZE="761281" MIMETYPE="application/pdf" OWNERID="82234-96686-1-PB.pdf" CHECKSUM="1cda0575531ff5d9a472bd4c1c5a7a7c" CHECKSUMTYPE="MD5"><METS:FLocat xlink:href="http://journals.fcla.edu/browardlegacy/article/viewFile/82234/79346" LOCTYPE="URL"/>
     </METS:file>

That gives an OWNERID that seems to match the name of the PDF for the Table of Contents article.

I don't know if you can connect all of the pieces, or if that's too much work.  It may be enough to just grab each dmdSec and turn it into a separate MODS file named after the corresponding fileSec file OWNERID, so in this case 82234-96686-1-PB.xml.

And inserting the same <extension> in each file would be helpful as well.

Would that be doable without too much programming effort?

Whatever we decide I'll mock up a prototype and try loading it.  

Before we go too far I'll check in with Joanne, because she did a presentation on FAU at yesterday's DISC call and I *thought* that she had mentioned something about pointing at OJS from Islandora.  I want to make sure that she don't have some sort of plan that would affect this migration.

**Comment by lydiam** [comment]
Joanne at FAU says that it's possible that Broward Legacy will stop being published

From Joanne's email:

 "It has also come to my attention that the contact for the Broward Legacy was forced into early retirement/or resigned unexpectedly so I do not know if that means the end of the journal but I will investigate that further. While it doesn’t hurt to have the journal in both Islandora/OJS it still requires work to migrate it especially since they are METs  files. You tell me what your thoughts are, I can FTP or drop in a staff folder all the PDFs for all issues but they are Article level PDFs and I am guessing that won’t work for Islandora serial tree development. If it would help greatly I can have a student create Whole Issue PDFs and provide those for FHP."

If Broward Legacy won't be published anymore it's probably worth moving all issues into Islandora because they're part of the Florida Heritage Collection.  If it's still going to be published then we have a dilemma - double-loading or omitting it from Islandora or OJS.

On hold until we figure out the future of the journal.

**Comment by lydiam** [comment]
It may be just as easy to use the Excel to MODS transformer to create article-level MODS.  It's probably worth testing before any programming is done.  Should UF proceed with its DigiTool migration there are a few UF serials that have this situation as well:  Florida Anthropologist, Florida Architect.

**Comment by wrandtkeflvc** [comment]
The status of this is that Broward Legacy was migrated with a single big PDF for each issue.

If article level PDFs were wanted, then it's possible to use this https://github.com/fsulib/ojsh to get the article level PDFs and metadata from Florida OJ.  (That will likely change with the move from OJS 2 to OJS 3 which likely will be in the next year.)

Should someone ask Joanne about this?
